be/src/main/java/com/forpets/be/BeApplication.java
be/src/main/java/com/forpets/be/global/auth/dto/response/SignupResponseDto.java

- FR-14
- SignupResponseDto에 LocalDateTime 추가
- BeApplication에 EnableJpaAuditing 어노테이션 추가하여
- BaseTimeEntity 작동하게 설정

FR-14 [BE] 응답 데이터에 생성일, 수정일 추가

---

be/.env.example
be/build.gradle
be/src/main/java/com/forpets/be/global/auth/controller/AuthController.java
be/src/main/java/com/forpets/be/global/auth/dto/request/LoginRequestDto.java
be/src/main/java/com/forpets/be/global/auth/dto/response/TokenResponseDto.java
be/src/main/java/com/forpets/be/global/auth/service/AuthService.java
be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
be/src/main/java/com/forpets/be/global/security/CustomUserDetailsService.java
be/src/main/java/com/forpets/be/global/security/handler/CustomAccessDeniedHandler.java
be/src/main/java/com/forpets/be/global/security/handler/JwtAuthenticationEntryPoint.java
be/src/main/java/com/forpets/be/global/security/jwt/JwtAuthenticationFilter.java
be/src/main/java/com/forpets/be/global/security/jwt/JwtTokenProvider.java
be/src/main/resources/application.properties

- FR-17
- jwt 토큰을 활용한 로그인 기능 구현
- jwt-secret key 환경변수 추가
- main에서 pull 받은 후 jwt secret key 환경변수 설정해야 함

FR-17 [BE] 로그인 기능 구현

---

fe/src/components/Header.jsx
fe/src/components/mypage/ProfileCard.jsx
fe/src/pages/MyPage.jsx
fe/src/router/index.jsx

- FR-15
- 마이페이지의 링크를 기존 /mypage → /my 로 수정
- AnimalDetail, AnimalList, VolunteerDetail, VolunteerList router 연결 추가
- 마이페이지에 속한 프로필, 나의 아이, 봉사글 카드 라우터 연결 추가
- 선택된 항목(프로필, 나의 아이, 나의 봉사글)에 대한 색상 전환

FR-15 [FE] 마이페이지 기초 구현

---

fe/index.html
fe/src/components/KakaoMap.jsx
fe/src/components/MainAnimalCard.jsx
fe/src/components/MainCard.jsx
fe/src/components/MainVolunteerCard.jsx
fe/src/pages/Home.jsx

- FR-20
- 메인페이지 레이아웃, 스타일 구현
- 메인페이지 나의아이 컴포넌트 레이아웃 스타일 구현

FR-20 [FE] 메인 페이지 구현

---

be/src/main/java/com/forpets/be/global/config/SecurityConfig.java

- FR-25
- SecuriryConfig에 cors를 추가 함

FR-25 [BE] CORS 설정 추가

---

fe/src/api/authApi.js
fe/src/pages/Signup.jsx

- FR-13
- 회원가입만 되게끔 일단 페이지만 구현
- cors랑 axios pull 받고 css, 이벤트 추가 및 수정 예정

FR-13 [FE] 회원가입 페이지 구현

---

fe/src/api/authApi.js
fe/src/pages/Signup.jsx

- FR-26
- css 형태만 잡음
- 닉네임 중복 검사 추가함.

FR-26 [FE] 회원가입 페이지 css 적용 및 이벤트 수정

---

fe/src/api/mypageApi.js
fe/src/components/mypage/ProfileCard.jsx
fe/src/components/mypage/ProfileEditCard.jsx
fe/src/pages/MyPage.jsx
fe/src/router/index.jsx

- FR-23
- commit 1
- 프로필 카드에 필요한 아이템 생성
- 로컬에서 파일(이미지) 업로드 로직 구현
- 회원정보 수정 버튼 생성
- 회원정보 수정 버튼 클릭 시 모달창 생성
- commit 2
- /api/my/profile로 api 조회하도록 로직 구현
- 추후 백엔드 마이페이지 회원정보 조회 API 구현 후 데이터 요청, 응답 확인해볼 예정
- commit 3
- ProfileEditCard 생성
- ProfileEditCard 라우터 연결 추가

FR-23 [FE] 마이페이지 프로필 카드 컴포넌트 구현

---

be/src/main/java/com/forpets/be/domain/user/my/controller/MyController.java
be/src/main/java/com/forpets/be/domain/user/my/dto/response/MyProfileResponseDto.java
be/src/main/java/com/forpets/be/domain/user/my/service/MyService.java

- FR-32
- 마이페이지에서 내 정보에 대해 조회하는 API 구현 완료
- /api/my/profile로 GET 요청

FR-32 [BE] 마이페이지 프로필 조회 API 구현

---

fe/package-lock.json
fe/package.json
fe/src/components/DaumPost.jsx
fe/src/components/KakaoMap.jsx
fe/src/pages/Home.jsx

- FR-30
- 메인페이지 지도 구현 (현재 보고있는 중앙이점 기준으로 주소표시, 클릭시 주소표시)
- 주소검색 기능 구현
- npm install react-daum-postcode (주소 api 사용을위한npm)
- npm i 하면 됩니다!

FR-30 [FE] 메인페이지 지도, 주소검색 구현

---

be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
be/src/main/resources/application.properties

- FR-36
- SecurityConfig에 배포 도메인 CORS 설정

FR-36 [BE] SecurityConfig에 cors 추가 적용

---

fe/src/api/axios.js

- FR-39
- axios.js 파일 accessToken을 헤더에 담아 백에 보내도록 연결

FR-39 [FE] axios 토큰 연결

---

fe/src/components/mypage/AnimalCard.jsx
fe/src/components/mypage/ProfileCard.jsx
fe/src/pages/MyPage.jsx

- FR-41
- 마이페이지 탭 버튼(프로필, 나의 아이, 나의 봉사글) 폰트 사이즈를 기본 -> text-lg 로 수정
- 컴포넌트 내 수정 정보에 대한 위치 통일
- 마이페이지 나의 아이 카드 컴포넌트 레이아웃, 스타일 구현

FR-41 [FE] 마이페이지 나의 아이 카드 컴포넌트 디자인 구현

---

fe/src/pages/Chat.jsx

FR-38 [FE]: 채팅 페이지 레이아웃, 스타일 구현

---

fe/src/components/mypage/AnimalCard.jsx
fe/src/pages/MyPage.jsx

- FR-43
- 마이페이지 레이아웃 구조를 main → section으로 수정
- 나의 아이 삭제 버튼 추가
- 나의 아이를 리스트처럼 구분할 수 있게 레이아웃, 스타일 수정

FR-43 [FE] 마이페이지 디자인 수정

---

fe/src/components/mypage/VolunteerCard.jsx

- FR-44
- 마이페이지 나의 봉사글 카드 컴포넌트 레이아웃, 스타일 구현

FR-44 [FE] 마이페이지 나의 봉사글 카드 컴포넌트 디자인 구현

---

fe/src/api/authApi.js
fe/src/pages/Signup.jsx

- FR-42
- smtp를 사용한 이메일 인증 코드 송신
- 수신된 인증 코드를 서버에서 값 대조하여 검증
- 모든 유효성과 인증 후 회원가입 버튼 활성화

FR-42 [FE] 회원가입 시 Gmail smtp를 사용한 이메일 인증 페이지 구현

---

fe/src/components/ChatUserCard.jsx
fe/src/pages/Chat.jsx

- FR-45
- 채팅 요청, 봉사자 카드 레이아웃 스타일 제작 완료
- 채팅페이지 레이아웃 스타일 제작 완료

FR-45 [FE] 채팅 페이지 스타일 구현

---

be/src/main/java/com/forpets/be/global/config/SecurityConfig.java

- FR-48
- logout 구현하기 위한 SecurityConfig에 .requestMatchers("/api/auth/logout).authenticated 추가

FR-48 [BE] 로그아웃 예외처리

---

fe/src/api/authApi.js
fe/src/api/axios.js
fe/src/store/slices/authSlice.js

- FR-47
- 로그인 페이지 리프레쉬 토큰 api연결 완료

FR-47 [FE] 로그인 페이지 리프레쉬 토큰 api연결

---

be/src/main/java/com/forpets/be/global/exeption/GlobalExceptionHandler.java
be/src/main/java/com/forpets/be/global/exeption/ResourceNotFoundException.java
be/src/main/resources/application.properties

- FR-53
- 전역적으로 예외처리를 하기 위해 global/exception 경로에 기능 구현
- GlobalExceptionHandler.java
- ResourceNotFoundException.java
- application.properties에 설정 추가

FR-53 [BE] Exception Handling

---

be/src/main/java/com/forpets/be/global/auth/service/AuthService.java
be/src/main/java/com/forpets/be/global/redis/RedisRepository.java

- FR-56
- 순환 참조를 해결하기 위해 RedisRepository Component 추가. AuthService에서 RedisRepository Bean을 참조하도록 재구성

FR-56 [BE] Redis 로직 분리 

---

fe/src/Layout/MainLayout.jsx
fe/src/components/Footer.jsx
fe/src/components/Header.jsx
fe/src/components/RescueAnimalCard.jsx
fe/src/components/RescueAnimalDetail.jsx
fe/src/pages/Chat.jsx
fe/src/pages/Home.jsx
fe/src/pages/RescueAnimals.jsx
fe/src/router/index.jsx

- FR-57
- 구조동물 페이지, 컴포넌트 레이아웃, 스타일, api연결 완료
- footer 컴포넌트 fix = 항상 모든요소의 제일 아래쪽에 위치하며 빈경우 화면의 하단에 붙도록 변경
fe .env 파일에
VITE_RESCUE_ANIMALS_KEY="sU2jtPOTQI1lNQtQwwNH5FR2Rf0+l/AX9M4/A+L7/K1HAxybD0BVOVtotamccTeMgbws24Zq1At5koZUypbw4g=="
추가

FR-57 [FE] 구조동물 페이지 레이아웃, 스타일, api연결, footer컴포넌트픽스

---

be/src/main/java/com/forpets/be/domain/chat/chatroom/controller/ChatRoomController.java
be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/request/ChatRoomRequestDto.java
be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/ChatRoomResponseDto.java
be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/ChatRoom.java
be/src/main/java/com/forpets/be/domain/chat/chatroom/entity/RoomState.java
be/src/main/java/com/forpets/be/domain/chat/chatroom/repository/ChatRoomRepository.java
be/src/main/java/com/forpets/be/domain/chat/chatroom/service/ChatRoomService.java

- FR-59
- 채팅방 생성 API 구현
- 나의 아이 등록글에 대한 개발이 진행 중이라 현재는 봉사글을 통한 채팅방 생성만 가능하도록 구현했음  (추후 나의 아이 등록글에 대한 채팅방 생성 코드도 추가할 예정)

FR-59 [BE] 채팅방 생성 API 구현

---

fe/src/components/Header.jsx
fe/src/components/RescueAnimalCard.jsx
fe/src/pages/RescueAnimalDetail.jsx
fe/src/pages/RescueAnimalList.jsx
fe/src/router/index.jsx

- FR-58
- 구조동물 디테일 페이지 레이아웃, 스타일 구현완료
- RescueAnimals.jsx 페이지에서 RescueAnimalDetail.jsx로 변경 (router에 추가함)

FR-58 [FE] 구조동물 디테일 페이지 제작

---

fe/src/api/animalsApi.js
fe/src/components/KakaoMap.jsx
fe/src/components/MainAnimalCard.jsx
fe/src/pages/Home.jsx

- FR-66
- 메인 페이지 나의 아이 api 연결완료
이미지는 테이블에 적용되면 넣겠습니다

FR-66 [FE] 메인페이지 나의아이 api 연결

---

be/src/main/java/com/forpets/be/domain/animal/controller/MyAnimalController.java
be/src/main/java/com/forpets/be/domain/animal/entity/MyAnimal.java
be/src/main/java/com/forpets/be/domain/animal/repository/MyAnimalRepository.java
be/src/main/java/com/forpets/be/domain/animal/service/MyAnimalService.java

- FR-67
- 개별 나의 아이 상세 조회 기능 구현
- 사용자별 나의 아이 전체 조회 기능 구현
- User entity의 builder patter에서 빠진 user 추가

FR-67 [BE] 나의 아이 개별 상세 조회

---

fe/src/components/KakaoMap.jsx

- FR-71
- 메인페이지 출발지 도착지 마커구현
- 요청자, 봉사자 클릭시에 요청자,봉사자의 출발지만 마커로 표시하도록 바꿀예정 입니다
- 도착지 정보는 추후에 상세페이지에 네비게이션 기능을 넣어도 괜찮을듯 합니다.
- 요쳥자, 봉사자 등록버튼 각각의 탭 클릭시 변화하도록 바꿀예정 입니다.

FR-71 [FE] 메인페이지 출발지 도착지 마커구현

---

fe/src/pages/ServiceStatus.jsx

FR-80  배포 테스트

---

.github/workflows/workflows.yml

- FR-81
- push 시 github action 실행되면서 aws ec2에 배포가 되어야 하는데
- 계속 며칠 전 구현했던 페이지만 보여서 해결중...

FR-81 배포 테스트

---

fe/src/components/KakaoMap.jsx
fe/src/components/MainAnimalCard.jsx
fe/src/components/MainVolunteerCard.jsx
fe/src/pages/Home.jsx

- FR-79
- 메인페이지 요청자, 봉사자 텝 클릭시 그에맞는 출발지 주소 마커구현 완료
- 텝 클릭시 주황색으로 활성

FR-79 [FE] 메인페이지 봉사자 마커 구현

---

fe/src/components/VolunteerCard.jsx
package-lock.json
package.json

- FR-90
- 수정사항 반영 및 리액트 모달 라이브러리 설치

FR-90[FE] 봉사자 등록 수정사항 반영

---

be/src/main/java/com/forpets/be/global/auth/controller/AuthController.java
be/src/main/java/com/forpets/be/global/auth/dto/response/TokenResponseDto.java
be/src/main/java/com/forpets/be/global/auth/service/AuthService.java
be/src/main/java/com/forpets/be/global/security/jwt/TokenAndIdDto.java

- FR-92
- 로그인 시 userId 전달 추가
- 재발급 시 userId 전달 추가

FR-92 [BE] 로그인 및 재발급 시 userId 전달 추가

---

fe/src/components/VolunteerCard.jsx
fe/src/pages/Login.jsx

- FR-93
- 
- 네이버 소셜 로그인 버튼 구현
- main에서 충돌 해결 안 한 부분 해결

FR-93 [FE]네이버 소셜 로그인 구현

---

.github/workflows/workflows.yml

- FR-96
- workflows.yml에서 env를 인식 안 해서
- 개행 인식 문제라고 하여 수정

FR-96 배포 테스트

---

fe/src/pages/RegisterAnimal.jsx

- FR-94
- 공개 버튼 기능 구현
- 로그인/비로그인에 따른 접근 기능 추가
- 각각의 입력란들의 기능에 맞게 설정들 추가

FR-94 [FE] 나의 아이 등록 기능 구현 및 수정

---

be/src/main/java/com/forpets/be/domain/servicevolunteer/controller/VolunteerController.java
be/src/main/java/com/forpets/be/domain/servicevolunteer/dto/request/ServiceVolunteerUpdateRequestDto.java
be/src/main/java/com/forpets/be/domain/servicevolunteer/entity/ServiceVolunteer.java
be/src/main/java/com/forpets/be/domain/servicevolunteer/service/VolunteerService.java
fe/src/components/VolunteerCard.jsx
fe/src/pages/VolunteerDetail.jsx

- FR-91
[BE] 봉사자 글 등록글 수정
포스트 맨에서 테스트함
_ 봉사자 글 등록 글 상세보기에서 동물유형의 영어로 나타나는 걸 한글로 표기하도록 코드를 갱신함

FR-91 [BE] 봉사자 글 등록 수정

---

fe/src/api/axios.js

- FR-101
- 토큰 만료 시 발생하는  401 에러 방지용 지연 시간 설정
-

FR-101 [FE] 토큰 만료 시 발생하는 401 에러 지연 시간 설정

---

be/src/main/java/com/forpets/be/global/exeption/GlobalExceptionHandler.java
be/src/main/java/com/forpets/be/global/security/handler/JwtAuthenticationEntryPoint.java
fe/package-lock.json

FR-107 배포 테스트

---

be/src/main/resources/application.yml

- FR-109
- 레디스 연결 시 localhost로 되어
- 레디스 환경변수 적용

FR-109 배포 테스트 4

---

be/src/main/java/com/forpets/be/domain/volunteerworkstatus/controller/VolunteerWorkStatusController.java
be/src/main/java/com/forpets/be/domain/volunteerworkstatus/dto/response/VolunteerWorkStatusListResponseDto.java
be/src/main/java/com/forpets/be/domain/volunteerworkstatus/repository/VolunteerWorkStatusRepository.java
be/src/main/java/com/forpets/be/domain/volunteerworkstatus/service/VolunteerWorkStatusService.java
fe/package-lock.json
fe/package.json

- FR-106
- 전체, 진행 중, 완료 상태에 대해 각각 다른 값을 입력받아서 데이터를 필터링 후 응답하도록 구현

FR-106 [BE] 이동봉사 현황 전체 조회 API 구현

---

fe/src/api/animalsApi.js
fe/src/components/AnimalCard.jsx
fe/src/pages/AnimalDetail.jsx
fe/src/pages/RegisterAnimal.jsx

- FR-100
- 나의 아이 디테일 페이지 구현
- 수정화면은 모달창으로 구현

FR-100 [FE] 나의 아이 상세페이지 구현

---

be/src/main/java/com/forpets/be/domain/animal/controller/MyAnimalController.java
be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalCreateRequestDto.java
be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalUpdateRequestDto.java

- 강아지 이름이 1자인 경우를 반영
- memo와 notice가 없을 경우를 위해 min=0으로 변경
- 응답코드를 OK -> CREATED, OK, UPDATED, DELETED 로 변경
- FR-110
- 강아지 이름이 1자인 경우를 반영 
- memo와 notice가 없을 경우를 위해 min=0으로 변경 
- 응답코드를 OK -> CREATED, OK, UPDATED, DELETED 로 변경

FR-110 [BE] 나의 아이 dto 및 응답코드 수정

---

be/src/main/resources/application.yml

- FR-113
application.yml의 redis 호스트를 localhost -> domain -> 레디스 컨테이너명으로 변경

FR-113 배포 테스트 5

---

be/src/main/java/com/forpets/be/domain/volunteerworkstatus/controller/VolunteerWorkStatusController.java
be/src/main/java/com/forpets/be/domain/volunteerworkstatus/repository/VolunteerWorkStatusRepository.java
be/src/main/java/com/forpets/be/domain/volunteerworkstatus/service/VolunteerWorkStatusService.java

- FR-111
- API Path 수정
- 이동봉사 현황 생성 API Path 수정
- 이동봉사 현황 전체 조회 API Path 수정
- 나의 이동봉사 현황 조회 API 구현
- 로그인한 사용자가 요청자 또는 봉사자로 참여했던 이동봉사 현황 조회하는 로직 구현
- 로그인한 사용자가 요청자 또는 봉사자로 참여했던 이동봉사 현황이 없는 경우를 검증하는 로직 구현

FR-111 [BE] 나의 이동봉사 현황 조회 API 구현

---

be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/RequestorChatRoomsResponseDto.java

- FR-114
- RequestorChatRoomResponseDto에 getServiceVolunteer() -> getVolunteerWork()로 수정

FR-114 [BE] 채팅 코드 수정

---

be/src/main/resources/application.yml

FR-115 배포 테스트 6

---

.github/workflows/workflows.yml

- FR-117
- 깃허브 액션 수정
- [긴급] 제목과는 다른 RedisConfig 브랜치로 했어요...

[FR-117] 깃허브액션 수정

---

.github/workflows/workflows.yml
be/src/main/java/com/forpets/be/global/config/RedisConfig.java

FR-117 RedisConfig 추가

---

.github/workflows/workflows.yml
be/src/main/java/com/forpets/be/RedisConnectionTestController.java
be/src/main/java/com/forpets/be/global/config/RedisConfig.java
be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
be/src/main/resources/application.yml

FR-117 배포 테스트

---

fe/src/pages/AnimalDetail.jsx

- FR-118
- 나의아이 페이지에서  로그인중인 사용자가 채팅시도시 봉사자로 등록 완료

FR-118 [FE] 나의아이 페이지 채팅 연결

---

be/src/main/java/com/forpets/be/RedisConnectionTestController.java
be/src/main/java/com/forpets/be/global/config/RedisConfig.java
be/src/main/resources/application.yml

FR-125 배포 테스트 8

---

fe/src/api/animalsApi.js

FR-127 [FE] endpont 수정

---

be/src/main/java/com/forpets/be/global/aws/AwsS3Config.java
be/src/main/java/com/forpets/be/global/aws/S3Service.java

FR-128 [BE] aws s3 구성 파일

---

be/src/main/resources/application.yml
fe/src/components/chat/ChatMessages.jsx
fe/src/pages/Login.jsx

- FR-131
- 스프링부트 환경변수 오작성 수정
- 리액트에서 환경변수 쓰려면
- VITE_ 로 시작해야 한다는걸 깜빡함 ㅎㅎ;

FR-131 환경 변수 수정

---

fe/src/pages/VolunteerWorkStatus.jsx

- FR-130
- 비 로그인 시에는 작동하는데
- 로그인 시 이동봉사현황 페이지 length 오류로 미작동하여 수정

FR-130 [FE] 이동 봉사 현황 페이지 수정

---

fe/src/components/chat/ChatMessages.jsx

FR-134 [FE] 채팅 페이지 코드 리펙토링

---

fe/src/api/volunteerWorkStatusApi.js
fe/src/components/PromiseModal.jsx
fe/src/components/VolunteerWorkStatusCard.jsx
fe/src/components/chat/ChatRoomHeader.jsx
fe/src/pages/Chat.jsx
fe/src/pages/VolunteerWorkStatus.jsx

- FR-135
- 이동봉사 현황 생성(약속잡기) 완료

FR-135 [FE] 이동봉사 현황 생성

---

be/src/main/java/com/forpets/be/domain/user/controller/UserController.java
be/src/main/java/com/forpets/be/domain/user/dto/request/UserPasswordRequestRecord.java
be/src/main/java/com/forpets/be/domain/user/repository/UserRepository.java
be/src/main/java/com/forpets/be/domain/user/service/UserService.java

- FR-133
- DB에 있는 비밀번호는 해싱되어 있으므로 matches 메서드를 통해 일치 여부를 확인

FR-133 [BE] 마이페이지 회원정보 수정 비밀번호 검증 API 구현

---

fe/src/components/mypage/AnimalCard.jsx
fe/src/components/mypage/ProfileCard.jsx
fe/src/components/mypage/VolunteerCard.jsx

- FR-138
- 마이페이지 나의 아이 컴포넌트 레이아웃 및 CSS 수정
- 마이페이지 나의 봉사글 카드 컴포넌트 레이아웃 및 CSS 수정

FR-138 [FE] 마이페이지 나의 아이, 나의 봉사글 카드 컴포넌트 수정

---

be/src/main/java/com/forpets/be/domain/volunteerwork/controller/VolunteerController.java
be/src/main/java/com/forpets/be/domain/volunteerwork/dto/response/MyVolunteerWorkListResponseDto.java
be/src/main/java/com/forpets/be/domain/volunteerwork/dto/response/MyVolunteerWorkResponseDto.java
be/src/main/java/com/forpets/be/domain/volunteerwork/repository/VolunteerWorkRepository.java
be/src/main/java/com/forpets/be/domain/volunteerwork/service/VolunteerWorkService.java
fe/src/api/volunteerApi.js

- FR-148
- MyPage 내 봉사글 조회 api 구현
- 컨트롤러 매핑 URL 변경
- 프론트 매핑 URL 변경
- 회원가입 페이지 구현

FR-148 [BE] 마이페이지 나의 봉사글 조회 API 구현

---

be/src/main/java/com/forpets/be/domain/animal/dto/request/MyAnimalUpdateRequestDto.java
be/src/main/java/com/forpets/be/domain/animal/dto/response/MyAnimalResponseDto.java
be/src/main/java/com/forpets/be/domain/animal/service/MyAnimalService.java

- FR-151
- 나의 아이 사진 변경시 s3에서 기존 사진 삭제하기 기능 구현

FR-151 [BE] 나의 아이 기존 사진 삭제 기능 구현

---

fe/src/api/animalsApi.js
fe/src/pages/RegisterAnimal.jsx

- FR-153
- 배포판에서 실행오류 잡기 위한 코드 정리 및  코드 재배포

FR-153 [FE] 나의 아이 등록 Content-Type 에러 수정

---

be/src/main/java/com/forpets/be/domain/volunteerwork/dto/response/MyVolunteerWorkResponseDto.java
fe/src/api/mypageApi.js
fe/src/components/mypage/VolunteerCard.jsx
fe/src/components/mypage/VolunteerCardList.jsx
fe/src/pages/MyPage.jsx
fe/src/router/index.jsx

- FR-150
- 마이페이지 나의 봉사글 조회 페이지 구현
- 백엔드 응답값 추가함

FR-150 [FE] 마이페이지 나의 봉사글 조회 API 연동

---

fe/src/components/mypage/AnimalCard.jsx
fe/src/components/mypage/AnimalCardList.jsx
fe/src/router/index.jsx

- FR-156
- 마이페이지 나의 아이 조회 api 연결

FR-156 [FE] 마이페이지 나의 아이 조회 API 연동

---

be/src/main/java/com/forpets/be/domain/chat/chatroom/dto/response/RequestorChatRoomsResponseDto.java

FR-162 [BE] 봉사글이 없는경우 예외처리

---

fe/src/pages/Login.jsx

- FR-163
- 회원가입 버튼 클릭 시 로그인 input창에 입력하라는 문구 나오는 오류 수정
- 회원가입 글자 클릭해야 회원가입 페이지로 넘어갔었는데
- 그냥 버튼 자체를 클릭 시 넘어가도록 수정

FR-163 [FE] 로그인 페이지 수정

---

fe/src/components/mypage/AnimalCard.jsx
fe/src/components/mypage/AnimalCardList.jsx
fe/src/components/mypage/VolunteerCardList.jsx
fe/src/pages/MyPage.jsx

FR-164 [FE] 마이페이지 스크롤 수정

---

be/src/main/java/com/forpets/be/domain/animal/controller/MyAnimalController.java
be/src/main/java/com/forpets/be/global/config/SecurityConfig.java
fe/src/components/RescueAnimalCard.jsx
fe/src/pages/RescueAnimalDetail.jsx

FR-170 [BE, FE]: AWS 공공데이터포털 이미지 프록시처리

---

fe/templates/https.conf.template

- FR-172
- 소셜 로그인 프록시 설정 명확히 함.
-

FR-172 [FE] 소셜 로그인 프록시 설정

---

fe/templates/https.conf.template

FR-173 [FE] 소셜 로그인 프록시 재설정2

---

fe/src/pages/Login.jsx

- FR-174
- 로그인 페이지 소셜 로그인 버튼 form 밖으로 뺌
-

FR-174 [FE] 로그인 페이지 수정

---

be/src/main/resources/application.yml

- FR-175
- redirect-uri: '{baseUrl}/login/oauth2/code/naver'
- 이거를
- redirect-uri: 'https://for-pets.me/login/oauth2/code/naver'
- 로 바꿔봄

FR-175 [BE] 네이버 소셜 로그인 redirect-uri 수정 테스트

---

fe/src/components/MainAnimalCard.jsx
fe/src/components/MainVolunteerCard.jsx
fe/src/components/volunteer/VolunteerCard.jsx
fe/src/components/volunteer/VolunteerEditModal.jsx
fe/src/pages/AnimalDetail.jsx
fe/src/pages/AnimalList.jsx
fe/src/pages/Home.jsx
fe/src/pages/RegisterAnimal.jsx
fe/src/pages/RegisterVolunteer.jsx
fe/src/pages/VolunteerDetail.jsx
fe/src/pages/VolunteerList.jsx

- FR-177
- 메인 홈 요청봉사 버튼클릭시 카드 모양, 구조 통일화, 반응형 구현
- 요청자, 봉사자 작성, 리스트, 디테일, 수정 페이지 통일화

FR-177 [FE] 홈, 요청 봉사자 페이지 ui 통일화

---

fe/src/pages/Signup.jsx

- FR-137
- 회원가입 페이지 리팩토링
- 인증 코드 타이머 추가
- 
- useEffact의 중요성을 깨달음...

FR-137 [FE] 회원가입 페이지 리펙토링
